#!/usr/bin/env bash
# Configures Eden (deps/eden) for the PS4 into build-eden/.
set -e
source "$(dirname "${BASH_SOURCE[0]}")/tools/env-build.sh"
unset OO_PS4_TOOLCHAIN
R=$NXO_ROOT
cmake -S $R/deps/eden -B $R/build-eden -G Ninja \
 -DCMAKE_TOOLCHAIN_FILE=$NXO_MIX/toolchain/eden-ps4.cmake -DPS4_BUILD_PKG=OFF \
 -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=OFF -DENABLE_QT=OFF -DYUZU_CMD=OFF -DYUZU_ROOM=OFF \
 -DYUZU_ROOM_STANDALONE=OFF -DYUZU_TESTS=OFF -DBUILD_TESTING=OFF -DENABLE_OPENGL=OFF -DENABLE_CUBEB=OFF \
 -DENABLE_WEB_SERVICE=OFF -DENABLE_LIBUSB=OFF -DYUZU_CRASH_DUMPS=OFF -DENABLE_WERROR=OFF \
 -Dzstd_FORCE_BUNDLED=ON -DBoost_FORCE_BUNDLED=ON -Dfmt_FORCE_BUNDLED=ON -DDYNARMIC_ENABLE_NO_EXECUTE_SUPPORT=OFF \
 -DYUZU_USE_EXTERNAL_FFMPEG=OFF -DYUZU_DOWNLOAD_TIME_ZONE_DATA=ON \
 -DYUZU_USE_BUNDLED_OPENSSL=OFF -DOpenSSL_FORCE_SYSTEM=ON -DOPENSSL_ROOT_DIR=$PS4_PREFIX \
 -DOPENSSL_INCLUDE_DIR=$PS4_PREFIX/include -DOPENSSL_SSL_LIBRARY=$PS4_PREFIX/lib/libssl.a \
 -DOPENSSL_CRYPTO_LIBRARY=$PS4_PREFIX/lib/libcrypto.a \
 -U "FFmpeg_*" -DFFMPEG_DIR=$PS4_PREFIX \
 -DCMAKE_PROJECT_yuzu_INCLUDE=$NXO_MIX/frontend/inject.cmake "$@"
