# Toolchain for building LLVM 18 libc++/libc++abi for the PS4 (OpenOrbis musl + orbis-compat).
# Only static libraries are produced, so try_compile never links.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
get_filename_component(_nxo_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(SDK "${_nxo_root}/sdk-dl/orbis-sdk-v1/sdk")
set(COMPAT "${_nxo_root}/sdk-dl/orbis-sdk-v1/orbis-compat")
if(CMAKE_HOST_WIN32)
  set(_x ".exe")
else()
  set(_x "")
endif()
# LLVM 18: $NXO_TOOLS/llvm/bin on Windows, /usr/lib/llvm-18/bin (or PATH) on Linux.
if(DEFINED ENV{NXO_TOOLS})
  set(LLVMBIN "$ENV{NXO_TOOLS}/llvm/bin/")
elseif(EXISTS "/usr/lib/llvm-18/bin")
  set(LLVMBIN "/usr/lib/llvm-18/bin/")
else()
  set(LLVMBIN "")
endif()
set(CMAKE_C_COMPILER "${LLVMBIN}clang${_x}")
set(CMAKE_CXX_COMPILER "${LLVMBIN}clang++${_x}")
set(CMAKE_ASM_COMPILER "${LLVMBIN}clang${_x}")
set(CMAKE_AR "${LLVMBIN}llvm-ar${_x}")
set(CMAKE_RANLIB "${LLVMBIN}llvm-ranlib${_x}")
set(CMAKE_C_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(CMAKE_ASM_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(_common "-nostdlibinc -fPIC -funwind-tables -D__PS4__ -DPS4 -D__ORBIS__ -D_BSD_SOURCE=1 -U__FreeBSD__ -isysroot ${SDK}")
set(OVERLAY "${_nxo_root}/toolchain/include-overlay")
set(CMAKE_C_FLAGS_INIT "${_common} -isystem ${OVERLAY} -isystem ${COMPAT}/include -isystem ${SDK}/include -include orbis_prefix.h")
set(CMAKE_CXX_FLAGS_INIT "${_common} -nostdinc++ -isystem ${OVERLAY} -isystem ${COMPAT}/include -isystem ${SDK}/include -include orbis_prefix.h")
set(CMAKE_ASM_FLAGS_INIT "${_common}")
