# Toolchain for building LLVM 18 libc++/libc++abi for the PS4 (OpenOrbis musl + orbis-compat).
# Only static libraries are produced, so try_compile never links.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(SDK "C:/Users/alejo/eden-ps4/sdk-dl/orbis-sdk-v1/sdk")
set(COMPAT "C:/Users/alejo/eden-ps4/sdk-dl/orbis-sdk-v1/orbis-compat")
set(LLVMBIN "C:/Users/alejo/soh-ps4/tools/llvm/bin")
set(CMAKE_C_COMPILER "${LLVMBIN}/clang.exe")
set(CMAKE_CXX_COMPILER "${LLVMBIN}/clang++.exe")
set(CMAKE_ASM_COMPILER "${LLVMBIN}/clang.exe")
set(CMAKE_AR "${LLVMBIN}/llvm-ar.exe")
set(CMAKE_RANLIB "${LLVMBIN}/llvm-ranlib.exe")
set(CMAKE_C_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(CMAKE_ASM_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(_common "-fPIC -funwind-tables -D__PS4__ -DPS4 -D__ORBIS__ -D_BSD_SOURCE=1 -U__FreeBSD__ -isysroot ${SDK}")
set(OVERLAY "C:/Users/alejo/eden-ps4/toolchain/include-overlay")
set(CMAKE_C_FLAGS_INIT "${_common} -isystem ${OVERLAY} -isystem ${COMPAT}/include -isystem ${SDK}/include -include orbis_prefix.h")
set(CMAKE_CXX_FLAGS_INIT "${_common} -nostdinc++ -isystem ${OVERLAY} -isystem ${COMPAT}/include -isystem ${SDK}/include -include orbis_prefix.h")
set(CMAKE_ASM_FLAGS_INIT "${_common}")
